# Generated by Django 5.2 on 2025-04-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0004_alter_products_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
