# Generated by Django 5.2 on 2025-04-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0011_customuser_address_customuser_is_seller_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
